# .streamlit/secrets.toml

[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/1UQZxEyP_JapwX5mu--9UtdcsrBJC3Fu4KbN9i7fd2sQ"
worksheet = "<worksheet-gid-or-folder-id>"  # worksheet GID or folder ID
type = "service_account"  # type of connection (service_account for service account auth)
project_id = "isa-registration"
private_key_id = "0360586fc02928fd242cbb038598e1d7227d6d88"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC+EVvzJmorl1Bn
HODQzZyqiKOLCwUy9zet9ZyAcfDhdYpTzqYaKCTEHee41XX4obd5iWNocGy/3jdz
aN2cQAGImc3bps3dtzm3VBfTBAnCvxCtGYMQozqLwoLdRiXCAC7w7N5OtY24Kh4f
eT+P9bk/xnJZF9hrHtnsiWzeHnox1Pzkd0+5+5jD7glA0O0hkG2lf2PiaJBZxtXo
dyf1syl+YNXX2UxVipob0wvjPXTSoU50W3vEFFJBMhR4nmsXS8HCts5MQt7sPF8m
mxvPYuPpOL5qzGJ9S6sghX33u1tfZFBO8fVDlRIMc3pEbXCcvKtBj05ud4OMiJOg
VmxPCUR9AgMBAAECggEAAy0ol3tunkxg0lxT8IFjKyFt9EKqo1Oo2U4nv6jH0QjF
F0n2kizWEnX6e6cLmexf89bFM8dfNeSpkhLwUy5pqCYD3/YdbiVkAEmWPVdNr3TA
e1gYDeTgc1n8lGSZ+HBG2I1o2LFljSydBMMiug3t+uAe5JjGq+Gf3DleuaaSPbdt
WZzuTh9s67Vb9nsVpT3wSko8jQ4xy0owScutWodO9imiLbTCYmJ3/tFTZ84MjJ3Z
65GIKVT4p0rOvMCg9KpS4FDqEtCB4wYGOUeTCXxn6UBbnwiOTorwt6gIwmT5qsQY
BF0wFHUqwUpXmFAnWZIBU2sULbj8cixw0zEAwXe0+QKBgQD1DmHVdE1ilRnuld6c
/usWuu0LbXdmRE9azwzIuAKjCl1afhFk+IGV+Qz/vAarJknm5YV6lqDPTZhDrXw1
s7nV88ysvSJ6rEm6xlvf3RnoCDEjb54sijfYXy/EWzN6Lkm8+E6bxThfFZ9IunJv
Rdk8YpW+G0I2SEHYZHMEvZsfRQKBgQDGjlHNAJ2qJLZhLT5dYcsjjsPvUu82eb5m
04lOp/GBnCK5CUXs0pSktFECmQ3rABnOa7ptqcSfHRki/w3xEbJmmqo63bOZPgpO
/bc+CTRhdZCa1M5qhGdhuJHBsSlglI5iYWaIYdjSaWVA/NzBte+riyTmNhHK+sro
5gfDUQtn2QKBgQCrl5CF6NQvDXyFBchFYnK3DdjiQZpzr61pRsYK3l5qT92iedgw
PZpvq16gy8ZXnY3t8hWPC147CnhuG1J4QAsGd5p/8kfsYiuWb0Lx9F4pjWLrD0NQ
qNAF4FEQS1Q2X6cefTh99pFMc1V/lZ5/sAc3M0jrPycT33DL1zp6vVGbiQKBgEyC
7xaWFCtKNlU///YwBv1OuEXyqWdOhoZNIW4D3VZaei7fWeimRM0rBsR/ghN6WHdo
n9A+SRwfNF599jtc3GgZVVuVru1wMLy7m+710Q91JCHluxzkpInNe60tvYoP9MYI
TmBjhA+guXnPdqnWl+J8nd1wHG8hMSuJ6JflFQYRAoGBAOVF92Ol4x9r/zejFKgb
Yso7KDkjTzGdXSgxtsmwUTDyLZ/jZ2rVR3FlndYOMNZLKjUmDTEMBWRXPWMePLEm
GmqLtCuYM38PKVqT92QXJaXSXUD67uKbfe37doOCXcmsvSEQqtzJwJoHYc2p/N2Q
4WcNr04N1SEwxqJQ8hHcy+54
-----END PRIVATE KEY-----"""
client_email = "keerthivasan@isa-registration.iam.gserviceaccount.com"
client_id = "105128829756602902365"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/keerthivasan%40isa-registration.iam.gserviceaccount.com"
